### ISSUE TITLE
Server: Todo Tasks

### ISSUE THREAD

**Issue by violet-dev** [project-violet/violet#479]
- [ ] User Info
   - [x] Register/Login/Logout
   - [ ] Integrate Discord Api
   - [ ] Supports Multi Device
- [x] View Record
   - [x] Connect Redis
   - [x] Real Time Rank
- [ ] Comment
  - [ ] Global Comment
  - [ ] Article Comment
- [ ] Bookmark Backup
- [ ] Integrate Message Search
